name: ci
on:
  push: 
    branches: 
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: checkout 
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
          
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.98.0'
          extended: true
          
      - name: Build
        run: hugo -D
        
      - name: Add CNAME
        run: echo "nekoram7.com" > public/CNAME
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: PureWhite216/PureWhite216.github.io
          publish_branch: main
          publish_dir: ./public
          commit_message: ${{ github.event.head_commit.message }}

